/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAtsScoreRouteImport } from './routes/ai-ats-score'
import { Route as AiCareerRouteImport } from './routes/ai-career'
import { Route as AiCareerRoadmapRouteImport } from './routes/ai-career-roadmap'
import { Route as AiCompanyMatchRouteImport } from './routes/ai-company-match'
import { Route as AiCoverLetterRouteImport } from './routes/ai-cover-letter'
import { Route as AiHistoryRouteImport } from './routes/ai-history'
import { Route as AiInterviewCoachRouteImport } from './routes/ai-interview-coach'
import { Route as AiLearningRouteImport } from './routes/ai-learning'
import { Route as AiMockInterviewRouteImport } from './routes/ai-mock-interview'
import { Route as AiPortfolioReviewRouteImport } from './routes/ai-portfolio-review'
import { Route as AiProgressRouteImport } from './routes/ai-progress'
import { Route as AiProjectReviewRouteImport } from './routes/ai-project-review'
import { Route as AiResumeAnalyzerRouteImport } from './routes/ai-resume-analyzer'
import { Route as AiResumeGeneratorRouteImport } from './routes/ai-resume-generator'
import { Route as AiSkillGapsRouteImport } from './routes/ai-skill-gaps'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as CareerScoreRouteImport } from './routes/career-score'
import { Route as CareerSnapshotRouteImport } from './routes/career-snapshot'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ConnectionsBackupRouteImport } from './routes/connections-backup'
import { Route as ConnectionsPremiumRouteImport } from './routes/connections-premium'
import { Route as ContributionsRouteImport } from './routes/contributions'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardAdaptiveRouteImport } from './routes/dashboard-adaptive'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IdentityHubRouteImport } from './routes/identity-hub'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioEditorRouteImport } from './routes/portfolio-editor'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UsernameSettingsRouteImport } from './routes/username-settings'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AnalyticsCodechefRouteImport } from './routes/analytics/codechef'
import { Route as AnalyticsCodeforcesRouteImport } from './routes/analytics/codeforces'
import { Route as AnalyticsGfgRouteImport } from './routes/analytics/gfg'
import { Route as AnalyticsGithubRouteImport } from './routes/analytics/github'
import { Route as AnalyticsHackerrankRouteImport } from './routes/analytics/hackerrank'
import { Route as AnalyticsLeetcodeRouteImport } from './routes/analytics/leetcode'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as UUsernameRecruiterRouteImport } from './routes/u/$username/recruiter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAtsScoreRoute = AiAtsScoreRouteImport.update({
  id: '/ai-ats-score',
  path: '/ai-ats-score',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCareerRoute = AiCareerRouteImport.update({
  id: '/ai-career',
  path: '/ai-career',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCareerRoadmapRoute = AiCareerRoadmapRouteImport.update({
  id: '/ai-career-roadmap',
  path: '/ai-career-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCompanyMatchRoute = AiCompanyMatchRouteImport.update({
  id: '/ai-company-match',
  path: '/ai-company-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoverLetterRoute = AiCoverLetterRouteImport.update({
  id: '/ai-cover-letter',
  path: '/ai-cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHistoryRoute = AiHistoryRouteImport.update({
  id: '/ai-history',
  path: '/ai-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInterviewCoachRoute = AiInterviewCoachRouteImport.update({
  id: '/ai-interview-coach',
  path: '/ai-interview-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLearningRoute = AiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMockInterviewRoute = AiMockInterviewRouteImport.update({
  id: '/ai-mock-interview',
  path: '/ai-mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPortfolioReviewRoute = AiPortfolioReviewRouteImport.update({
  id: '/ai-portfolio-review',
  path: '/ai-portfolio-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProgressRoute = AiProgressRouteImport.update({
  id: '/ai-progress',
  path: '/ai-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProjectReviewRoute = AiProjectReviewRouteImport.update({
  id: '/ai-project-review',
  path: '/ai-project-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResumeAnalyzerRoute = AiResumeAnalyzerRouteImport.update({
  id: '/ai-resume-analyzer',
  path: '/ai-resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResumeGeneratorRoute = AiResumeGeneratorRouteImport.update({
  id: '/ai-resume-generator',
  path: '/ai-resume-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSkillGapsRoute = AiSkillGapsRouteImport.update({
  id: '/ai-skill-gaps',
  path: '/ai-skill-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerScoreRoute = CareerScoreRouteImport.update({
  id: '/career-score',
  path: '/career-score',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSnapshotRoute = CareerSnapshotRouteImport.update({
  id: '/career-snapshot',
  path: '/career-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsBackupRoute = ConnectionsBackupRouteImport.update({
  id: '/connections-backup',
  path: '/connections-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsPremiumRoute = ConnectionsPremiumRouteImport.update({
  id: '/connections-premium',
  path: '/connections-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionsRoute = ContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdaptiveRoute = DashboardAdaptiveRouteImport.update({
  id: '/dashboard-adaptive',
  path: '/dashboard-adaptive',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityHubRoute = IdentityHubRouteImport.update({
  id: '/identity-hub',
  path: '/identity-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioEditorRoute = PortfolioEditorRouteImport.update({
  id: '/portfolio-editor',
  path: '/portfolio-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSettingsRoute = UsernameSettingsRouteImport.update({
  id: '/username-settings',
  path: '/username-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCodechefRoute = AnalyticsCodechefRouteImport.update({
  id: '/codechef',
  path: '/codechef',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCodeforcesRoute = AnalyticsCodeforcesRouteImport.update({
  id: '/codeforces',
  path: '/codeforces',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsGfgRoute = AnalyticsGfgRouteImport.update({
  id: '/gfg',
  path: '/gfg',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsGithubRoute = AnalyticsGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsHackerrankRoute = AnalyticsHackerrankRouteImport.update({
  id: '/hackerrank',
  path: '/hackerrank',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsLeetcodeRoute = AnalyticsLeetcodeRouteImport.update({
  id: '/leetcode',
  path: '/leetcode',
  getParentRoute: () => AnalyticsRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRecruiterRoute = UUsernameRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => UUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/ai-ats-score': typeof AiAtsScoreRoute
  '/ai-career': typeof AiCareerRoute
  '/ai-career-roadmap': typeof AiCareerRoadmapRoute
  '/ai-company-match': typeof AiCompanyMatchRoute
  '/ai-cover-letter': typeof AiCoverLetterRoute
  '/ai-history': typeof AiHistoryRoute
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ai-learning': typeof AiLearningRoute
  '/ai-mock-interview': typeof AiMockInterviewRoute
  '/ai-portfolio-review': typeof AiPortfolioReviewRoute
  '/ai-progress': typeof AiProgressRoute
  '/ai-project-review': typeof AiProjectReviewRoute
  '/ai-resume-analyzer': typeof AiResumeAnalyzerRoute
  '/ai-resume-generator': typeof AiResumeGeneratorRoute
  '/ai-skill-gaps': typeof AiSkillGapsRoute
  '/ai-usage': typeof AiUsageRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/career-score': typeof CareerScoreRoute
  '/career-snapshot': typeof CareerSnapshotRoute
  '/change-password': typeof ChangePasswordRoute
  '/connections': typeof ConnectionsRoute
  '/connections-backup': typeof ConnectionsBackupRoute
  '/connections-premium': typeof ConnectionsPremiumRoute
  '/contributions': typeof ContributionsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-adaptive': typeof DashboardAdaptiveRoute
  '/error': typeof ErrorRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity-hub': typeof IdentityHubRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/portfolio-editor': typeof PortfolioEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/username-settings': typeof UsernameSettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics/codechef': typeof AnalyticsCodechefRoute
  '/analytics/codeforces': typeof AnalyticsCodeforcesRoute
  '/analytics/gfg': typeof AnalyticsGfgRoute
  '/analytics/github': typeof AnalyticsGithubRoute
  '/analytics/hackerrank': typeof AnalyticsHackerrankRoute
  '/analytics/leetcode': typeof AnalyticsLeetcodeRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/recruiter': typeof UUsernameRecruiterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/ai-ats-score': typeof AiAtsScoreRoute
  '/ai-career': typeof AiCareerRoute
  '/ai-career-roadmap': typeof AiCareerRoadmapRoute
  '/ai-company-match': typeof AiCompanyMatchRoute
  '/ai-cover-letter': typeof AiCoverLetterRoute
  '/ai-history': typeof AiHistoryRoute
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ai-learning': typeof AiLearningRoute
  '/ai-mock-interview': typeof AiMockInterviewRoute
  '/ai-portfolio-review': typeof AiPortfolioReviewRoute
  '/ai-progress': typeof AiProgressRoute
  '/ai-project-review': typeof AiProjectReviewRoute
  '/ai-resume-analyzer': typeof AiResumeAnalyzerRoute
  '/ai-resume-generator': typeof AiResumeGeneratorRoute
  '/ai-skill-gaps': typeof AiSkillGapsRoute
  '/ai-usage': typeof AiUsageRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/career-score': typeof CareerScoreRoute
  '/career-snapshot': typeof CareerSnapshotRoute
  '/change-password': typeof ChangePasswordRoute
  '/connections': typeof ConnectionsRoute
  '/connections-backup': typeof ConnectionsBackupRoute
  '/connections-premium': typeof ConnectionsPremiumRoute
  '/contributions': typeof ContributionsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-adaptive': typeof DashboardAdaptiveRoute
  '/error': typeof ErrorRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity-hub': typeof IdentityHubRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/portfolio-editor': typeof PortfolioEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/username-settings': typeof UsernameSettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics/codechef': typeof AnalyticsCodechefRoute
  '/analytics/codeforces': typeof AnalyticsCodeforcesRoute
  '/analytics/gfg': typeof AnalyticsGfgRoute
  '/analytics/github': typeof AnalyticsGithubRoute
  '/analytics/hackerrank': typeof AnalyticsHackerrankRoute
  '/analytics/leetcode': typeof AnalyticsLeetcodeRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/recruiter': typeof UUsernameRecruiterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/ai-ats-score': typeof AiAtsScoreRoute
  '/ai-career': typeof AiCareerRoute
  '/ai-career-roadmap': typeof AiCareerRoadmapRoute
  '/ai-company-match': typeof AiCompanyMatchRoute
  '/ai-cover-letter': typeof AiCoverLetterRoute
  '/ai-history': typeof AiHistoryRoute
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ai-learning': typeof AiLearningRoute
  '/ai-mock-interview': typeof AiMockInterviewRoute
  '/ai-portfolio-review': typeof AiPortfolioReviewRoute
  '/ai-progress': typeof AiProgressRoute
  '/ai-project-review': typeof AiProjectReviewRoute
  '/ai-resume-analyzer': typeof AiResumeAnalyzerRoute
  '/ai-resume-generator': typeof AiResumeGeneratorRoute
  '/ai-skill-gaps': typeof AiSkillGapsRoute
  '/ai-usage': typeof AiUsageRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/career-score': typeof CareerScoreRoute
  '/career-snapshot': typeof CareerSnapshotRoute
  '/change-password': typeof ChangePasswordRoute
  '/connections': typeof ConnectionsRoute
  '/connections-backup': typeof ConnectionsBackupRoute
  '/connections-premium': typeof ConnectionsPremiumRoute
  '/contributions': typeof ContributionsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-adaptive': typeof DashboardAdaptiveRoute
  '/error': typeof ErrorRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/identity-hub': typeof IdentityHubRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/portfolio-editor': typeof PortfolioEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/username-settings': typeof UsernameSettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics/codechef': typeof AnalyticsCodechefRoute
  '/analytics/codeforces': typeof AnalyticsCodeforcesRoute
  '/analytics/gfg': typeof AnalyticsGfgRoute
  '/analytics/github': typeof AnalyticsGithubRoute
  '/analytics/hackerrank': typeof AnalyticsHackerrankRoute
  '/analytics/leetcode': typeof AnalyticsLeetcodeRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/recruiter': typeof UUsernameRecruiterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/achievements'
    | '/activity'
    | '/admin'
    | '/ai-ats-score'
    | '/ai-career'
    | '/ai-career-roadmap'
    | '/ai-company-match'
    | '/ai-cover-letter'
    | '/ai-history'
    | '/ai-interview-coach'
    | '/ai-learning'
    | '/ai-mock-interview'
    | '/ai-portfolio-review'
    | '/ai-progress'
    | '/ai-project-review'
    | '/ai-resume-analyzer'
    | '/ai-resume-generator'
    | '/ai-skill-gaps'
    | '/ai-usage'
    | '/analytics'
    | '/assistant'
    | '/auth-callback'
    | '/career-score'
    | '/career-snapshot'
    | '/change-password'
    | '/connections'
    | '/connections-backup'
    | '/connections-premium'
    | '/contributions'
    | '/copilot'
    | '/dashboard'
    | '/dashboard-adaptive'
    | '/error'
    | '/features'
    | '/forgot-password'
    | '/identity-hub'
    | '/interview'
    | '/login'
    | '/portfolio-editor'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/resume-builder'
    | '/settings'
    | '/signup'
    | '/statistics'
    | '/unauthorized'
    | '/username-settings'
    | '/verify-email'
    | '/analytics/codechef'
    | '/analytics/codeforces'
    | '/analytics/gfg'
    | '/analytics/github'
    | '/analytics/hackerrank'
    | '/analytics/leetcode'
    | '/u/$username'
    | '/u/$username/recruiter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/achievements'
    | '/activity'
    | '/admin'
    | '/ai-ats-score'
    | '/ai-career'
    | '/ai-career-roadmap'
    | '/ai-company-match'
    | '/ai-cover-letter'
    | '/ai-history'
    | '/ai-interview-coach'
    | '/ai-learning'
    | '/ai-mock-interview'
    | '/ai-portfolio-review'
    | '/ai-progress'
    | '/ai-project-review'
    | '/ai-resume-analyzer'
    | '/ai-resume-generator'
    | '/ai-skill-gaps'
    | '/ai-usage'
    | '/analytics'
    | '/assistant'
    | '/auth-callback'
    | '/career-score'
    | '/career-snapshot'
    | '/change-password'
    | '/connections'
    | '/connections-backup'
    | '/connections-premium'
    | '/contributions'
    | '/copilot'
    | '/dashboard'
    | '/dashboard-adaptive'
    | '/error'
    | '/features'
    | '/forgot-password'
    | '/identity-hub'
    | '/interview'
    | '/login'
    | '/portfolio-editor'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/resume-builder'
    | '/settings'
    | '/signup'
    | '/statistics'
    | '/unauthorized'
    | '/username-settings'
    | '/verify-email'
    | '/analytics/codechef'
    | '/analytics/codeforces'
    | '/analytics/gfg'
    | '/analytics/github'
    | '/analytics/hackerrank'
    | '/analytics/leetcode'
    | '/u/$username'
    | '/u/$username/recruiter'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/achievements'
    | '/activity'
    | '/admin'
    | '/ai-ats-score'
    | '/ai-career'
    | '/ai-career-roadmap'
    | '/ai-company-match'
    | '/ai-cover-letter'
    | '/ai-history'
    | '/ai-interview-coach'
    | '/ai-learning'
    | '/ai-mock-interview'
    | '/ai-portfolio-review'
    | '/ai-progress'
    | '/ai-project-review'
    | '/ai-resume-analyzer'
    | '/ai-resume-generator'
    | '/ai-skill-gaps'
    | '/ai-usage'
    | '/analytics'
    | '/assistant'
    | '/auth-callback'
    | '/career-score'
    | '/career-snapshot'
    | '/change-password'
    | '/connections'
    | '/connections-backup'
    | '/connections-premium'
    | '/contributions'
    | '/copilot'
    | '/dashboard'
    | '/dashboard-adaptive'
    | '/error'
    | '/features'
    | '/forgot-password'
    | '/identity-hub'
    | '/interview'
    | '/login'
    | '/portfolio-editor'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/resume-builder'
    | '/settings'
    | '/signup'
    | '/statistics'
    | '/unauthorized'
    | '/username-settings'
    | '/verify-email'
    | '/analytics/codechef'
    | '/analytics/codeforces'
    | '/analytics/gfg'
    | '/analytics/github'
    | '/analytics/hackerrank'
    | '/analytics/leetcode'
    | '/u/$username'
    | '/u/$username/recruiter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AchievementsRoute: typeof AchievementsRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AiAtsScoreRoute: typeof AiAtsScoreRoute
  AiCareerRoute: typeof AiCareerRoute
  AiCareerRoadmapRoute: typeof AiCareerRoadmapRoute
  AiCompanyMatchRoute: typeof AiCompanyMatchRoute
  AiCoverLetterRoute: typeof AiCoverLetterRoute
  AiHistoryRoute: typeof AiHistoryRoute
  AiInterviewCoachRoute: typeof AiInterviewCoachRoute
  AiLearningRoute: typeof AiLearningRoute
  AiMockInterviewRoute: typeof AiMockInterviewRoute
  AiPortfolioReviewRoute: typeof AiPortfolioReviewRoute
  AiProgressRoute: typeof AiProgressRoute
  AiProjectReviewRoute: typeof AiProjectReviewRoute
  AiResumeAnalyzerRoute: typeof AiResumeAnalyzerRoute
  AiResumeGeneratorRoute: typeof AiResumeGeneratorRoute
  AiSkillGapsRoute: typeof AiSkillGapsRoute
  AiUsageRoute: typeof AiUsageRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CareerScoreRoute: typeof CareerScoreRoute
  CareerSnapshotRoute: typeof CareerSnapshotRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ConnectionsBackupRoute: typeof ConnectionsBackupRoute
  ConnectionsPremiumRoute: typeof ConnectionsPremiumRoute
  ContributionsRoute: typeof ContributionsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DashboardAdaptiveRoute: typeof DashboardAdaptiveRoute
  ErrorRoute: typeof ErrorRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IdentityHubRoute: typeof IdentityHubRoute
  InterviewRoute: typeof InterviewRoute
  LoginRoute: typeof LoginRoute
  PortfolioEditorRoute: typeof PortfolioEditorRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResumeRoute: typeof ResumeRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatisticsRoute: typeof StatisticsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UsernameSettingsRoute: typeof UsernameSettingsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ats-score': {
      id: '/ai-ats-score'
      path: '/ai-ats-score'
      fullPath: '/ai-ats-score'
      preLoaderRoute: typeof AiAtsScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-career': {
      id: '/ai-career'
      path: '/ai-career'
      fullPath: '/ai-career'
      preLoaderRoute: typeof AiCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-career-roadmap': {
      id: '/ai-career-roadmap'
      path: '/ai-career-roadmap'
      fullPath: '/ai-career-roadmap'
      preLoaderRoute: typeof AiCareerRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-company-match': {
      id: '/ai-company-match'
      path: '/ai-company-match'
      fullPath: '/ai-company-match'
      preLoaderRoute: typeof AiCompanyMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-cover-letter': {
      id: '/ai-cover-letter'
      path: '/ai-cover-letter'
      fullPath: '/ai-cover-letter'
      preLoaderRoute: typeof AiCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-history': {
      id: '/ai-history'
      path: '/ai-history'
      fullPath: '/ai-history'
      preLoaderRoute: typeof AiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-interview-coach': {
      id: '/ai-interview-coach'
      path: '/ai-interview-coach'
      fullPath: '/ai-interview-coach'
      preLoaderRoute: typeof AiInterviewCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-learning': {
      id: '/ai-learning'
      path: '/ai-learning'
      fullPath: '/ai-learning'
      preLoaderRoute: typeof AiLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mock-interview': {
      id: '/ai-mock-interview'
      path: '/ai-mock-interview'
      fullPath: '/ai-mock-interview'
      preLoaderRoute: typeof AiMockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-portfolio-review': {
      id: '/ai-portfolio-review'
      path: '/ai-portfolio-review'
      fullPath: '/ai-portfolio-review'
      preLoaderRoute: typeof AiPortfolioReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-progress': {
      id: '/ai-progress'
      path: '/ai-progress'
      fullPath: '/ai-progress'
      preLoaderRoute: typeof AiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-project-review': {
      id: '/ai-project-review'
      path: '/ai-project-review'
      fullPath: '/ai-project-review'
      preLoaderRoute: typeof AiProjectReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-resume-analyzer': {
      id: '/ai-resume-analyzer'
      path: '/ai-resume-analyzer'
      fullPath: '/ai-resume-analyzer'
      preLoaderRoute: typeof AiResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-resume-generator': {
      id: '/ai-resume-generator'
      path: '/ai-resume-generator'
      fullPath: '/ai-resume-generator'
      preLoaderRoute: typeof AiResumeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-skill-gaps': {
      id: '/ai-skill-gaps'
      path: '/ai-skill-gaps'
      fullPath: '/ai-skill-gaps'
      preLoaderRoute: typeof AiSkillGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-score': {
      id: '/career-score'
      path: '/career-score'
      fullPath: '/career-score'
      preLoaderRoute: typeof CareerScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-snapshot': {
      id: '/career-snapshot'
      path: '/career-snapshot'
      fullPath: '/career-snapshot'
      preLoaderRoute: typeof CareerSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections-backup': {
      id: '/connections-backup'
      path: '/connections-backup'
      fullPath: '/connections-backup'
      preLoaderRoute: typeof ConnectionsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections-premium': {
      id: '/connections-premium'
      path: '/connections-premium'
      fullPath: '/connections-premium'
      preLoaderRoute: typeof ConnectionsPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributions': {
      id: '/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof ContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-adaptive': {
      id: '/dashboard-adaptive'
      path: '/dashboard-adaptive'
      fullPath: '/dashboard-adaptive'
      preLoaderRoute: typeof DashboardAdaptiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-hub': {
      id: '/identity-hub'
      path: '/identity-hub'
      fullPath: '/identity-hub'
      preLoaderRoute: typeof IdentityHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-editor': {
      id: '/portfolio-editor'
      path: '/portfolio-editor'
      fullPath: '/portfolio-editor'
      preLoaderRoute: typeof PortfolioEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/username-settings': {
      id: '/username-settings'
      path: '/username-settings'
      fullPath: '/username-settings'
      preLoaderRoute: typeof UsernameSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/codechef': {
      id: '/analytics/codechef'
      path: '/codechef'
      fullPath: '/analytics/codechef'
      preLoaderRoute: typeof AnalyticsCodechefRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/codeforces': {
      id: '/analytics/codeforces'
      path: '/codeforces'
      fullPath: '/analytics/codeforces'
      preLoaderRoute: typeof AnalyticsCodeforcesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/gfg': {
      id: '/analytics/gfg'
      path: '/gfg'
      fullPath: '/analytics/gfg'
      preLoaderRoute: typeof AnalyticsGfgRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/github': {
      id: '/analytics/github'
      path: '/github'
      fullPath: '/analytics/github'
      preLoaderRoute: typeof AnalyticsGithubRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/hackerrank': {
      id: '/analytics/hackerrank'
      path: '/hackerrank'
      fullPath: '/analytics/hackerrank'
      preLoaderRoute: typeof AnalyticsHackerrankRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/leetcode': {
      id: '/analytics/leetcode'
      path: '/leetcode'
      fullPath: '/analytics/leetcode'
      preLoaderRoute: typeof AnalyticsLeetcodeRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/recruiter': {
      id: '/u/$username/recruiter'
      path: '/recruiter'
      fullPath: '/u/$username/recruiter'
      preLoaderRoute: typeof UUsernameRecruiterRouteImport
      parentRoute: typeof UUsernameRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsCodechefRoute: typeof AnalyticsCodechefRoute
  AnalyticsCodeforcesRoute: typeof AnalyticsCodeforcesRoute
  AnalyticsGfgRoute: typeof AnalyticsGfgRoute
  AnalyticsGithubRoute: typeof AnalyticsGithubRoute
  AnalyticsHackerrankRoute: typeof AnalyticsHackerrankRoute
  AnalyticsLeetcodeRoute: typeof AnalyticsLeetcodeRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsCodechefRoute: AnalyticsCodechefRoute,
  AnalyticsCodeforcesRoute: AnalyticsCodeforcesRoute,
  AnalyticsGfgRoute: AnalyticsGfgRoute,
  AnalyticsGithubRoute: AnalyticsGithubRoute,
  AnalyticsHackerrankRoute: AnalyticsHackerrankRoute,
  AnalyticsLeetcodeRoute: AnalyticsLeetcodeRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface UUsernameRouteChildren {
  UUsernameRecruiterRoute: typeof UUsernameRecruiterRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameRecruiterRoute: UUsernameRecruiterRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AchievementsRoute: AchievementsRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AiAtsScoreRoute: AiAtsScoreRoute,
  AiCareerRoute: AiCareerRoute,
  AiCareerRoadmapRoute: AiCareerRoadmapRoute,
  AiCompanyMatchRoute: AiCompanyMatchRoute,
  AiCoverLetterRoute: AiCoverLetterRoute,
  AiHistoryRoute: AiHistoryRoute,
  AiInterviewCoachRoute: AiInterviewCoachRoute,
  AiLearningRoute: AiLearningRoute,
  AiMockInterviewRoute: AiMockInterviewRoute,
  AiPortfolioReviewRoute: AiPortfolioReviewRoute,
  AiProgressRoute: AiProgressRoute,
  AiProjectReviewRoute: AiProjectReviewRoute,
  AiResumeAnalyzerRoute: AiResumeAnalyzerRoute,
  AiResumeGeneratorRoute: AiResumeGeneratorRoute,
  AiSkillGapsRoute: AiSkillGapsRoute,
  AiUsageRoute: AiUsageRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CareerScoreRoute: CareerScoreRoute,
  CareerSnapshotRoute: CareerSnapshotRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConnectionsRoute: ConnectionsRoute,
  ConnectionsBackupRoute: ConnectionsBackupRoute,
  ConnectionsPremiumRoute: ConnectionsPremiumRoute,
  ContributionsRoute: ContributionsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DashboardAdaptiveRoute: DashboardAdaptiveRoute,
  ErrorRoute: ErrorRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IdentityHubRoute: IdentityHubRoute,
  InterviewRoute: InterviewRoute,
  LoginRoute: LoginRoute,
  PortfolioEditorRoute: PortfolioEditorRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResumeRoute: ResumeRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatisticsRoute: StatisticsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UsernameSettingsRoute: UsernameSettingsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
